name: Enviar código por correo
on:
  repository_dispatch:
    types: [send-code]
  workflow_dispatch:
    inputs:
      tipo_doc:
        description: 'Tipo de documento'
        required: true
        type: string
      num_doc:
        description: 'Número de documento'
        required: true
        type: string
      correo:
        description: 'Correo electrónico'
        required: true
        type: string

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener datos del payload o inputs
        id: get-data
        run: |
          # Usar datos de workflow_dispatch o repository_dispatch
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "correo=${{ github.event.inputs.correo }}" >> $GITHUB_OUTPUT
            echo "codigo=${{ github.event.inputs.codigo || $(printf "%06d" $RANDOM) }}" >> $GITHUB_OUTPUT
            echo "tipo_doc=${{ github.event.inputs.tipo_doc }}" >> $GITHUB_OUTPUT
            echo "num_doc=${{ github.event.inputs.num_doc }}" >> $GITHUB_OUTPUT
          else
            echo "correo=${{ github.event.client_payload.correo }}" >> $GITHUB_OUTPUT
            echo "codigo=${{ github.event.client_payload.codigo }}" >> $GITHUB_OUTPUT
            echo "tipo_doc=${{ github.event.client_payload.tipo_doc }}" >> $GITHUB_OUTPUT
            echo "num_doc=${{ github.event.client_payload.num_doc }}" >> $GITHUB_OUTPUT
          fi

      - name: Llamada a SendGrid API
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.sendgrid.com/v3/mail/send'
          method: 'POST'
          customHeaders: '{"Authorization":"Bearer ${{ secrets.SENDGRID_API_KEY }}", "Content-Type":"application/json"}'
          data: >
            {
              "personalizations": [{"to": [{"email": "${{ steps.get-data.outputs.correo }}"}]}],
              "from": {"email": "administracion@misemilla.org"},
              "subject": "Código de Acceso - Actualización Registros",
              "content": [{"type": "text/plain", "value": "¡Hola!\nTu código de validación es: ${{ steps.get-data.outputs.codigo }}\nDatos registrados:\n- Tipo de documento: ${{ steps.get-data.outputs.tipo_doc }}\n- Número de documento: ${{ steps.get-data.outputs.num_doc }}"}]
            }
            
