name: Enviar código por correo

on:
  repository_dispatch:
    types: [solicitar-codigo]

jobs:
  enviar-correo:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar correo con SendGrid
        uses: fjogeleit/http-request-action@v1
        with:
          url: https://api.sendgrid.com/v3/mail/send
          method: POST
          customHeaders: >
            {
              "Authorization": "Bearer ${{ secrets.SENDGRID_API_KEY }}",
              "Content-Type": "application/json"
            }
          data: >
            {
              "personalizations": [
                {
                  "to": [
                    {
                      "email": "${{ github.event.client_payload.correo }}"
                    }
                  ]
                }
              ],
              "from": {
                "email": "administracion@misemilla.org"
              },
              "subject": "Código de Acceso",
              "content": [
                {
                  "type": "text/plain",
                  "value": "Tu código de verificación es: ${{ github.event.client_payload.codigo }}"
                }
              ]
            }
