name: Enviar código por correo
on:
  repository_dispatch:
    types: [send-code]
  workflow_dispatch: # Permite ejecutar el workflow manualmente para pruebas

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Obtener datos de prueba o del payload
        id: get-data
        run: |
          # Para pruebas: usa un correo fijo, luego lo cambias por el del payload
          echo "correo=haralcan16@gmail.com" >> $GITHUB_OUTPUT
          echo "codigo=123456" >> $GITHUB_OUTPUT
          echo "tipo_doc=CEDULA_CIUDADANIA" >> $GITHUB_OUTPUT
          echo "num_doc=79662020" >> $GITHUB_OUTPUT

      - name: Llamada a SendGrid API
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.sendgrid.com/v3/mail/send'
          method: 'POST'
          customHeaders: '{"Authorization":"Bearer ${{ secrets.SENDGRID_API_KEY }}", "Content-Type":"application/json"}'
          data: >
            {
              "personalizations": [{"to": [{"email": "${{ steps.get-data.outputs.correo }}"}]}],
              "from": {"email": "administracion@misemilla.org"},
              "subject": "PRUEBA - Código de Acceso",
              "content": [{"type": "text/plain", "value": "PRUEBA - Tu código es: ${{ steps.get-data.outputs.codigo }}"}]
            }
            
